name: Sanity test

on:
  push:
  pull_request:
  create:

jobs:
    
  workflow-sanity-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.4'
      - name: Install td
        run: |
          gem install td
      - name: Install workflow module
        env:
          TD_API_ENDPOINT: https://api.treasuredata.com
          TD_API_KEY: ${{ secrets.TD_API_KEY }}
        run: |
          yes | td -e "${TD_API_ENDPOINT}" -k "${TD_API_KEY}" workflow
      - name: Run workflow sanity test
        env:
          TD_API_ENDPOINT: https://api-development.treasuredata.com
          TD_API_KEY: ${{ secrets.TD_API_KEY }}
        run: |
          chmod +x .github/workflows/scripts/workflow-sanity-test.sh
          .github/workflows/scripts/workflow-sanity-test.sh
